<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DisplayPlant;

class PlantCareSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plantCareData = [
            'AGLAONEMA' => [
                'care_watering' => 'Water when top 1-2 inches of soil is dry, typically once a week. Reduce watering in winter. Avoid overwatering as it can cause root rot.',
                'care_sunlight' => 'Thrives in low to medium indirect light. Can tolerate low light conditions. Avoid direct sunlight which can scorch leaves.',
                'care_soil' => 'Well-draining potting mix with peat moss and perlite. Prefers slightly acidic soil (pH 5.6-6.5).',
                'care_temperature' => 'Ideal temperature: 65-80°F (18-27°C). Avoid temperatures below 60°F (15°C). Protect from cold drafts.',
                'care_humidity' => 'Prefers moderate to high humidity (60-70%). Mist leaves regularly or use a humidity tray. Can tolerate average household humidity.',
                'care_fertilizing' => 'Feed monthly during spring and summer with balanced liquid fertilizer diluted to half strength. Reduce feeding in fall and winter.',
                'care_pruning' => 'Remove yellow or damaged leaves at the base. Prune to maintain shape and encourage bushier growth. Clean leaves regularly to remove dust.',
                'care_propagation' => 'Propagate through stem cuttings or division. Best done in spring. Root cuttings in water or moist soil.',
                'care_pests' => 'Watch for spider mites, mealybugs, and scale. Treat with insecticidal soap or neem oil. Maintain good air circulation.',
                'care_growth_rate' => 'Slow to moderate grower. Reaches 1-3 feet tall indoors. Repot every 2-3 years in spring.',
                'care_toxicity' => 'Toxic to pets and humans if ingested. Contains calcium oxalate crystals. Keep away from children and pets. May cause skin irritation.',
                'care_notes' => 'Excellent air purifier. Very low maintenance and perfect for beginners. Variegated varieties need slightly more light to maintain color patterns.',
            ],
            'BASIL' => [
                'care_watering' => 'Water regularly to keep soil consistently moist but not waterlogged. Water at the base to avoid wetting leaves. Needs more water in hot weather.',
                'care_sunlight' => 'Requires 6-8 hours of direct sunlight daily. Can tolerate partial shade in hot climates. Grows well under grow lights indoors.',
                'care_soil' => 'Rich, well-draining soil with organic matter. pH 6.0-7.0. Add compost for nutrients.',
                'care_temperature' => 'Thrives in warm temperatures: 70-90°F (21-32°C). Very sensitive to frost. Bring indoors when temperature drops below 50°F (10°C).',
                'care_humidity' => 'Prefers moderate humidity (40-60%). Good air circulation prevents fungal diseases.',
                'care_fertilizing' => 'Feed every 2-3 weeks with balanced liquid fertilizer or fish emulsion. Avoid over-fertilizing which reduces flavor.',
                'care_pruning' => 'Pinch off flower buds to encourage leaf growth. Harvest regularly from the top to promote bushier growth. Cut stems above leaf nodes.',
                'care_propagation' => 'Easy to propagate from stem cuttings in water. Roots develop in 1-2 weeks. Also grows from seeds.',
                'care_pests' => 'Watch for aphids, Japanese beetles, and slugs. Use organic pest control. Companion plant with tomatoes to deter pests.',
                'care_growth_rate' => 'Fast grower. Reaches 12-24 inches tall. Ready to harvest in 3-4 weeks from planting.',
                'care_toxicity' => 'Non-toxic to humans and pets. Safe for culinary use. Rich in vitamins and antioxidants.',
                'care_notes' => 'Popular culinary herb. Best flavor before flowering. Harvest in morning after dew dries. Freezes well for winter use.',
            ],
            'BAY LEAF' => [
                'care_watering' => 'Water when top inch of soil is dry. Prefers slightly dry conditions over wet. Reduce watering in winter.',
                'care_sunlight' => 'Full sun to partial shade. Needs at least 4-6 hours of sunlight daily. Can grow indoors near bright window.',
                'care_soil' => 'Well-draining soil with sand or perlite. pH 6.0-7.0. Tolerates poor soil but grows better in fertile soil.',
                'care_temperature' => 'Hardy in zones 8-10. Prefers 60-75°F (15-24°C). Can tolerate brief cold snaps but protect from hard frost.',
                'care_humidity' => 'Tolerates average humidity. Mist occasionally if growing indoors in dry conditions.',
                'care_fertilizing' => 'Feed monthly during growing season with balanced fertilizer. Reduce feeding in winter.',
                'care_pruning' => 'Prune in spring to maintain shape and size. Remove dead or damaged branches. Can be trained as topiary.',
                'care_propagation' => 'Propagate from semi-hardwood cuttings in summer. Can also grow from seeds but very slow.',
                'care_pests' => 'Generally pest-resistant. Watch for scale insects and psyllids. Treat with horticultural oil.',
                'care_growth_rate' => 'Slow grower. Can reach 10-60 feet outdoors but easily kept smaller in containers. Long-lived plant.',
                'care_toxicity' => 'Leaves are safe for culinary use when dried. Fresh leaves can be bitter. Non-toxic to humans but may cause digestive upset in pets.',
                'care_notes' => 'Essential culinary herb. Leaves have better flavor when dried. Harvest mature leaves year-round. Store dried leaves in airtight container.',
            ],
            'BLUE PLUMBAGO' => [
                'care_watering' => 'Water regularly during growing season, allowing soil to dry slightly between waterings. Drought-tolerant once established. Reduce watering in winter.',
                'care_sunlight' => 'Full sun to partial shade. Blooms best with 6+ hours of direct sunlight. Can tolerate some shade but flowers less.',
                'care_soil' => 'Well-draining soil. Tolerates various soil types including sandy and clay. pH 6.0-7.5.',
                'care_temperature' => 'Hardy in zones 8-11. Prefers 60-85°F (15-29°C). Dies back in frost but returns from roots in spring.',
                'care_humidity' => 'Tolerates average to high humidity. Adaptable to various conditions.',
                'care_fertilizing' => 'Feed monthly during growing season with balanced fertilizer. Promotes abundant flowering.',
                'care_pruning' => 'Prune in late winter or early spring before new growth. Cut back by 1/3 to maintain shape. Deadhead spent flowers to encourage more blooms.',
                'care_propagation' => 'Propagate from softwood cuttings in spring or summer. Also spreads by underground stems.',
                'care_pests' => 'Generally pest-free. Occasionally affected by spider mites or whiteflies. Good air circulation prevents issues.',
                'care_growth_rate' => 'Fast grower. Can reach 6-10 feet tall and wide. Blooms spring through fall.',
                'care_toxicity' => 'Generally considered non-toxic but may cause mild stomach upset if ingested. Sap may irritate sensitive skin.',
                'care_notes' => 'Beautiful sky-blue flowers attract butterflies. Excellent for hedges, borders, or containers. Heat and drought tolerant once established.',
            ],
            'BOSTON FERN' => [
                'care_watering' => 'Keep soil consistently moist but not soggy. Water when top inch feels dry. Needs more frequent watering in warm weather. Mist regularly.',
                'care_sunlight' => 'Bright indirect light. Avoid direct sunlight which burns fronds. Tolerates low light but grows slower.',
                'care_soil' => 'Rich, well-draining potting mix with peat moss. Prefers slightly acidic soil (pH 5.0-5.5).',
                'care_temperature' => 'Ideal temperature: 60-75°F (15-24°C). Avoid temperatures below 50°F (10°C) and above 85°F (29°C).',
                'care_humidity' => 'Requires high humidity (50-80%). Mist daily, use humidity tray, or place in bathroom. Low humidity causes brown fronds.',
                'care_fertilizing' => 'Feed monthly during growing season with diluted liquid fertilizer. Use half-strength balanced fertilizer.',
                'care_pruning' => 'Remove brown or dead fronds at the base. Trim runners to maintain shape. Prune in spring for best results.',
                'care_propagation' => 'Propagate by division in spring. Separate runners with roots attached. Can also grow from spores but difficult.',
                'care_pests' => 'Watch for spider mites, mealybugs, and scale. Increase humidity to prevent spider mites. Treat with insecticidal soap.',
                'care_growth_rate' => 'Moderate grower. Can reach 2-3 feet tall and wide. Repot annually in spring.',
                'care_toxicity' => 'Non-toxic to pets and humans. Safe for homes with children and animals.',
                'care_notes' => 'Classic houseplant and excellent air purifier. Sensitive to chemicals in tap water - use filtered or rainwater. Thrives in hanging baskets.',
            ],
            'BOUGAINVILLEA' => [
                'care_watering' => 'Water deeply but infrequently. Allow soil to dry between waterings. Drought-tolerant once established. Reduce watering in winter to encourage blooming.',
                'care_sunlight' => 'Full sun required. Needs at least 6 hours of direct sunlight daily for best flowering. More sun equals more blooms.',
                'care_soil' => 'Well-draining soil. Tolerates poor soil. pH 5.5-6.5. Add sand or perlite for drainage.',
                'care_temperature' => 'Hardy in zones 9-11. Prefers 70-85°F (21-29°C). Protect from frost. Can be grown in containers and moved indoors.',
                'care_humidity' => 'Tolerates low to moderate humidity. Very adaptable to dry conditions.',
                'care_fertilizing' => 'Feed monthly during growing season with low-nitrogen, high-phosphorus fertilizer to promote blooming. Avoid over-fertilizing.',
                'care_pruning' => 'Prune after flowering to control size and shape. Can be trained as vine, shrub, or tree. Wear gloves as thorns are sharp.',
                'care_propagation' => 'Propagate from semi-hardwood cuttings in spring or summer. Root in well-draining medium.',
                'care_pests' => 'Watch for aphids, caterpillars, and mealybugs. Generally pest-resistant. Treat with neem oil if needed.',
                'care_growth_rate' => 'Fast grower. Can reach 15-40 feet if not pruned. Blooms spring through fall in warm climates.',
                'care_toxicity' => 'Sap may cause skin irritation. Mildly toxic if ingested - may cause digestive upset. Keep away from pets and children.',
                'care_notes' => 'Spectacular colorful bracts (not true flowers). Stress from drought and root restriction promotes better blooming. Excellent for tropical landscapes.',
            ],
            'CAT\'S WHISKERS' => [
                'care_watering' => 'Water regularly to keep soil evenly moist. Increase watering during hot weather. Avoid waterlogging.',
                'care_sunlight' => 'Full sun to partial shade. Needs 4-6 hours of sunlight daily. Afternoon shade in hot climates.',
                'care_soil' => 'Well-draining, fertile soil rich in organic matter. pH 6.0-7.0.',
                'care_temperature' => 'Tropical plant. Prefers 65-85°F (18-29°C). Not frost-tolerant. Grow as annual in cold climates.',
                'care_humidity' => 'Prefers moderate to high humidity. Tolerates average humidity with regular watering.',
                'care_fertilizing' => 'Feed every 2-3 weeks during growing season with balanced liquid fertilizer. Promotes continuous blooming.',
                'care_pruning' => 'Deadhead spent flowers to encourage more blooms. Pinch tips to promote bushier growth. Cut back in late winter.',
                'care_propagation' => 'Easy to propagate from stem cuttings. Root in water or moist soil. Also grows from seeds.',
                'care_pests' => 'Generally pest-free. Occasionally affected by aphids or whiteflies. Use insecticidal soap.',
                'care_growth_rate' => 'Moderate to fast grower. Reaches 2-4 feet tall. Blooms continuously in warm weather.',
                'care_toxicity' => 'Non-toxic. Used in traditional medicine. Safe around pets and children.',
                'care_notes' => 'Unique white or purple flowers with long stamens resembling cat whiskers. Attracts butterflies and hummingbirds. Medicinal herb used for kidney health.',
            ],
            'DATE PALM' => [
                'care_watering' => 'Water deeply but infrequently. Allow soil to dry between waterings. Drought-tolerant once established. Young palms need more frequent watering.',
                'care_sunlight' => 'Full sun. Needs 6-8 hours of direct sunlight daily. Tolerates intense heat and sun.',
                'care_soil' => 'Well-draining sandy or loamy soil. Tolerates poor soil and salt. pH 6.0-8.0.',
                'care_temperature' => 'Hardy in zones 9-11. Tolerates extreme heat up to 120°F (49°C). Can survive brief cold to 15°F (-9°C) when mature.',
                'care_humidity' => 'Tolerates low humidity. Very drought-resistant once established.',
                'care_fertilizing' => 'Feed 2-3 times per year with palm fertilizer containing micronutrients. Apply in spring, summer, and fall.',
                'care_pruning' => 'Remove only dead or damaged fronds. Never cut green fronds as it weakens the palm. Prune seed stalks if not harvesting dates.',
                'care_propagation' => 'Propagate from offshoots (pups) at base. Remove when 2-3 feet tall. Can grow from seeds but takes many years.',
                'care_pests' => 'Watch for palm weevils, scale, and spider mites. Maintain palm health to prevent infestations.',
                'care_growth_rate' => 'Slow grower. Takes 4-8 years to produce fruit. Can reach 50-80 feet tall outdoors.',
                'care_toxicity' => 'Non-toxic. Produces edible dates. Safe around pets and children.',
                'care_notes' => 'Ancient fruit tree cultivated for thousands of years. Requires male and female trees for fruit production. Very heat and drought tolerant.',
            ],
            'GIANT OR DRAGON' => [
                'care_watering' => 'Water regularly during growing season. Needs consistent moisture but well-drained soil. Established plants are drought-tolerant.',
                'care_sunlight' => 'Full sun to partial shade. Prefers 4-6 hours of sunlight daily. Tolerates shade better than most bamboos.',
                'care_soil' => 'Rich, well-draining soil with organic matter. pH 6.0-6.5. Mulch to retain moisture.',
                'care_temperature' => 'Hardy in zones 8-11. Tolerates temperatures down to 15°F (-9°C). Prefers warm tropical to subtropical climates.',
                'care_humidity' => 'Prefers moderate to high humidity. Tolerates various humidity levels.',
                'care_fertilizing' => 'Feed in spring with high-nitrogen fertilizer. Apply compost or organic matter annually.',
                'care_pruning' => 'Remove dead or damaged culms at ground level. Thin crowded clumps to improve air circulation. Prune in late winter.',
                'care_propagation' => 'Propagate by division of clumps. Separate rhizomes with shoots attached. Best done in spring.',
                'care_pests' => 'Generally pest-resistant. Occasionally affected by aphids or mealybugs. Good air circulation prevents issues.',
                'care_growth_rate' => 'Very fast grower. Can grow 3-4 feet per day during peak season. Reaches 60-100 feet tall with 4-6 inch diameter culms.',
                'care_toxicity' => 'Non-toxic. Shoots are edible when young. Safe around pets and children.',
                'care_notes' => 'One of the largest bamboo species. Clumping type (non-invasive). Used for construction, furniture, and edible shoots. Excellent for privacy screens.',
            ],
            'GOLDEN MIAGOS' => [
                'care_watering' => 'Water regularly to keep soil evenly moist during growing season. Reduce watering in winter. Avoid waterlogging.',
                'care_sunlight' => 'Full sun to partial shade. Needs 4-6 hours of sunlight daily for best color. Golden foliage develops best in bright light.',
                'care_soil' => 'Well-draining, fertile soil. pH 6.0-7.0. Add organic matter for nutrients.',
                'care_temperature' => 'Tropical plant. Prefers 65-85°F (18-29°C). Protect from frost. Can be grown in containers.',
                'care_humidity' => 'Prefers moderate to high humidity. Mist regularly if growing indoors.',
                'care_fertilizing' => 'Feed monthly during growing season with balanced fertilizer. Promotes healthy foliage growth.',
                'care_pruning' => 'Prune to maintain shape and size. Remove dead or damaged leaves. Pinch tips to encourage bushier growth.',
                'care_propagation' => 'Propagate from stem cuttings. Root in water or moist soil. Best done in spring or summer.',
                'care_pests' => 'Watch for aphids, mealybugs, and spider mites. Treat with insecticidal soap or neem oil.',
                'care_growth_rate' => 'Moderate grower. Reaches 2-4 feet tall. Compact growth habit.',
                'care_toxicity' => 'Generally non-toxic but verify specific variety. Keep away from pets as precaution.',
                'care_notes' => 'Attractive golden-yellow foliage. Excellent for adding color to gardens and containers. Low maintenance ornamental plant.',
            ],
            'GOLDEN PANDANUS' => [
                'care_watering' => 'Water when top inch of soil is dry. Drought-tolerant once established. Avoid overwatering which causes root rot.',
                'care_sunlight' => 'Full sun to partial shade. Golden color develops best in bright light. Tolerates some shade.',
                'care_soil' => 'Well-draining sandy or loamy soil. Tolerates poor soil and salt. pH 6.0-7.5.',
                'care_temperature' => 'Tropical plant. Hardy in zones 10-11. Prefers 60-85°F (15-29°C). Protect from frost.',
                'care_humidity' => 'Tolerates low to high humidity. Very adaptable to coastal conditions.',
                'care_fertilizing' => 'Feed 2-3 times per year with balanced fertilizer. Avoid over-fertilizing.',
                'care_pruning' => 'Remove dead or damaged leaves at base. Wear gloves as leaves have sharp spines. Prune to control size.',
                'care_propagation' => 'Propagate from offshoots (pups) that form at base. Remove when well-developed.',
                'care_pests' => 'Generally pest-resistant. Occasionally affected by scale or mealybugs. Treat with horticultural oil.',
                'care_growth_rate' => 'Slow to moderate grower. Can reach 6-15 feet tall. Long-lived plant.',
                'care_toxicity' => 'Non-toxic but leaves have sharp spines. Handle with care. Keep away from walkways.',
                'care_notes' => 'Striking golden-striped foliage. Excellent architectural plant. Very salt and wind tolerant. Perfect for coastal landscapes.',
            ],
            'KALUMPIT' => [
                'care_watering' => 'Water regularly when young. Once established, drought-tolerant. Deep watering encourages strong root system.',
                'care_sunlight' => 'Full sun. Needs at least 6 hours of direct sunlight daily. Tolerates intense tropical sun.',
                'care_soil' => 'Well-draining soil. Tolerates various soil types including clay and sandy. pH 6.0-7.5.',
                'care_temperature' => 'Tropical tree. Prefers 70-95°F (21-35°C). Not frost-tolerant. Thrives in warm, humid climates.',
                'care_humidity' => 'Prefers high humidity. Tolerates moderate humidity once established.',
                'care_fertilizing' => 'Feed young trees 2-3 times per year with balanced fertilizer. Mature trees need minimal fertilization.',
                'care_pruning' => 'Prune to shape when young. Remove dead or crossing branches. Minimal pruning needed once established.',
                'care_propagation' => 'Propagate from seeds or cuttings. Seeds germinate readily. Best planted directly in ground.',
                'care_pests' => 'Generally pest-resistant. Occasionally affected by caterpillars. Maintain tree health for pest resistance.',
                'care_growth_rate' => 'Fast grower. Can reach 30-50 feet tall. Provides quick shade.',
                'care_toxicity' => 'Non-toxic. Fruit is edible. Leaves used in traditional medicine. Safe around children and pets.',
                'care_notes' => 'Native Philippine tree. Produces edible fruit. Excellent shade tree. Used for timber and traditional medicine. Attracts birds and wildlife.',
            ],
            'ORGANIC FERTILIZER' => [
                'care_watering' => 'Not applicable - this is a fertilizer product, not a living plant.',
                'care_sunlight' => 'Store in cool, dry place away from direct sunlight to maintain quality.',
                'care_soil' => 'Apply to soil as directed. Works with all soil types. Improves soil structure and fertility.',
                'care_temperature' => 'Store at room temperature. Keep away from extreme heat or cold.',
                'care_humidity' => 'Store in dry conditions. Keep container sealed to prevent moisture absorption.',
                'care_fertilizing' => 'This IS the fertilizer. Apply according to package directions. Use for vegetables, flowers, trees, and lawns.',
                'care_pruning' => 'Not applicable to fertilizer product.',
                'care_propagation' => 'Not applicable to fertilizer product.',
                'care_pests' => 'Store properly to prevent contamination. Keep away from pests and rodents.',
                'care_growth_rate' => 'Improves plant growth rate when applied correctly. Results visible in 2-4 weeks.',
                'care_toxicity' => 'Generally safe but avoid ingestion. Keep away from children and pets. Wash hands after handling.',
                'care_notes' => 'Organic fertilizer enriches soil with natural nutrients. Slow-release formula. Improves soil health and microbial activity. Environmentally friendly alternative to chemical fertilizers.',
            ],
            'PAPYRUS' => [
                'care_watering' => 'Loves water. Keep soil constantly moist or grow in standing water. Can grow in ponds or water gardens. Never let soil dry out.',
                'care_sunlight' => 'Full sun to partial shade. Needs 4-6 hours of sunlight daily. Tolerates some shade.',
                'care_soil' => 'Rich, heavy soil or aquatic planting medium. Can grow in pure water. pH 6.0-8.0.',
                'care_temperature' => 'Hardy in zones 9-11. Prefers 60-85°F (15-29°C). Protect from frost. Can be grown indoors.',
                'care_humidity' => 'Loves high humidity. Perfect for water gardens, ponds, or bog gardens.',
                'care_fertilizing' => 'Feed monthly during growing season with aquatic plant fertilizer or balanced liquid fertilizer.',
                'care_pruning' => 'Remove dead or brown stems at base. Cut back in late winter before new growth. Divide clumps every 2-3 years.',
                'care_propagation' => 'Propagate by division of rhizomes. Can also root stem cuttings in water. Very easy to propagate.',
                'care_pests' => 'Generally pest-free. Occasionally affected by aphids. Rinse with water to remove.',
                'care_growth_rate' => 'Fast grower. Reaches 4-8 feet tall. Can spread vigorously in ideal conditions.',
                'care_toxicity' => 'Non-toxic to humans and pets. Safe for water gardens with fish.',
                'care_notes' => 'Ancient plant used to make paper in Egypt. Distinctive umbrella-like flower heads. Excellent for water features and bog gardens. Architectural statement plant.',
            ],
            'PEANUT' => [
                'care_watering' => 'Water regularly to keep soil evenly moist, especially during flowering and pod development. Needs 1-2 inches per week. Reduce watering near harvest.',
                'care_sunlight' => 'Full sun required. Needs 6-8 hours of direct sunlight daily for good yield.',
                'care_soil' => 'Well-draining, loose sandy loam. pH 5.9-6.3. Add calcium (gypsum) for better pod development.',
                'care_temperature' => 'Warm season crop. Needs 120-150 frost-free days. Optimal temperature: 70-85°F (21-29°C). Plant after last frost.',
                'care_humidity' => 'Tolerates moderate humidity. Good air circulation prevents fungal diseases.',
                'care_fertilizing' => 'Low nitrogen needs (legume fixes own nitrogen). Apply phosphorus and potassium at planting. Add calcium when flowering begins.',
                'care_pruning' => 'No pruning needed. Allow plants to grow naturally. Avoid disturbing plants when pegs enter soil.',
                'care_propagation' => 'Grow from raw, unroasted peanut seeds. Plant 1-2 inches deep after last frost.',
                'care_pests' => 'Watch for aphids, thrips, and leaf miners. Use row covers early season. Practice crop rotation.',
                'care_growth_rate' => 'Matures in 120-150 days. Harvest when leaves turn yellow. Dig carefully to avoid breaking pods.',
                'care_toxicity' => 'Non-toxic. Produces edible peanuts. Common allergen - handle with care if allergies present.',
                'care_notes' => 'Unique growth habit - flowers above ground, pods develop underground. Excellent nitrogen-fixing cover crop. Harvest and cure properly for storage.',
            ],
            'RED CANNA' => [
                'care_watering' => 'Water regularly to keep soil moist. Needs consistent moisture during growing season. Can tolerate wet conditions.',
                'care_sunlight' => 'Full sun to partial shade. Needs at least 4-6 hours of sunlight daily. More sun produces more flowers.',
                'care_soil' => 'Rich, moist soil with organic matter. Tolerates various soil types. pH 6.0-6.5.',
                'care_temperature' => 'Hardy in zones 7-11. Prefers 70-85°F (21-29°C). Rhizomes can be dug and stored in cold climates.',
                'care_humidity' => 'Tolerates high humidity. Thrives in tropical and subtropical conditions.',
                'care_fertilizing' => 'Feed monthly during growing season with balanced fertilizer. High phosphorus promotes blooming.',
                'care_pruning' => 'Deadhead spent flowers to encourage more blooms. Remove dead leaves. Cut back to ground after frost.',
                'care_propagation' => 'Propagate by dividing rhizomes in spring. Each division should have 2-3 eyes. Very easy to propagate.',
                'care_pests' => 'Watch for caterpillars, slugs, and Japanese beetles. Generally pest-resistant. Remove damaged leaves.',
                'care_growth_rate' => 'Fast grower. Reaches 3-6 feet tall. Blooms summer through fall.',
                'care_toxicity' => 'Mildly toxic if ingested. May cause digestive upset. Keep away from pets and children.',
                'care_notes' => 'Bold tropical appearance with large leaves and bright red flowers. Excellent for borders and containers. Attracts hummingbirds and butterflies.',
            ],
            'SPIDER LILY' => [
                'care_watering' => 'Water regularly during growing season. Prefers consistently moist soil. Can grow in shallow water or bog conditions.',
                'care_sunlight' => 'Full sun to partial shade. Needs 4-6 hours of sunlight daily. Blooms best in bright light.',
                'care_soil' => 'Rich, moist to wet soil. Tolerates clay and sandy soils. pH 6.0-7.5. Can grow in water gardens.',
                'care_temperature' => 'Hardy in zones 8-11. Prefers 65-85°F (18-29°C). Tolerates brief cold but protect from hard frost.',
                'care_humidity' => 'Prefers high humidity. Excellent for water features and coastal gardens.',
                'care_fertilizing' => 'Feed in spring with balanced fertilizer. Apply compost annually. Minimal feeding needed.',
                'care_pruning' => 'Remove spent flowers and dead leaves. Cut back foliage after frost. Divide clumps every 3-4 years.',
                'care_propagation' => 'Propagate by dividing bulbs in spring or fall. Separate offsets and replant. Also grows from seeds.',
                'care_pests' => 'Generally pest-free. Occasionally affected by slugs or snails. Use organic controls.',
                'care_growth_rate' => 'Moderate grower. Reaches 1-2 feet tall. Blooms in summer with fragrant white flowers.',
                'care_toxicity' => 'All parts toxic if ingested. Contains alkaloids. Keep away from children and pets. Handle bulbs with care.',
                'care_notes' => 'Stunning white spider-like flowers with sweet fragrance. Blooms appear before or with foliage. Excellent for water gardens, ponds, and wet areas. Attracts butterflies.',
            ],
            'GREEN FOUNTAIN GRASS' => [
                'care_watering' => 'Water regularly during the growing season, keeping soil consistently moist but not waterlogged. Reduce watering in winter. Established plants are moderately drought-tolerant.',
                'care_sunlight' => 'Full sun to partial shade. Prefers at least 6 hours of direct sunlight daily for best growth and flowering. Can tolerate light afternoon shade in hot climates.',
                'care_soil' => 'Well-draining soil with moderate fertility. Adapts to various soil types including sandy, loamy, and clay soils. Prefers slightly acidic to neutral pH (6.0-7.0).',
                'care_temperature' => 'Hardy in zones 5-9. Tolerates temperatures from -20°C to 35°C. Dies back in winter in colder zones but returns in spring. Protect from harsh winter winds.',
                'care_humidity' => 'Adaptable to various humidity levels. Prefers moderate humidity (40-60%) but tolerates both dry and humid conditions once established.',
                'care_fertilizing' => 'Apply balanced slow-release fertilizer in early spring. Light feeding is sufficient - over-fertilizing can cause floppy growth. Compost mulch provides adequate nutrients.',
                'care_pruning' => 'Cut back dead foliage to ground level in late winter or early spring before new growth emerges. Remove spent flower plumes to maintain appearance or leave for winter interest.',
                'care_propagation' => 'Divide clumps in spring every 3-4 years. Dig up the entire clump and separate into sections with roots attached. Can also grow from seed sown in spring.',
                'care_pests' => 'Generally pest and disease resistant. Occasionally affected by rust or leaf spot in humid conditions. Good air circulation helps prevent fungal issues. Deer and rabbit resistant.',
                'care_growth_rate' => 'Moderate to fast growth rate. Reaches mature size of 60-90cm tall and 60-75cm wide in 2-3 growing seasons. Forms attractive fountain-shaped clumps.',
                'care_toxicity' => 'Non-toxic to humans and pets. Safe for gardens with children and animals.',
                'care_notes' => 'Excellent ornamental grass for borders, mass plantings, or containers. Produces attractive bottlebrush-like flower plumes in late summer that persist into winter. Provides movement and texture in the garden. Low maintenance once established. Attracts birds who feed on seeds.',
            ],
        ];

        foreach ($plantCareData as $plantName => $careData) {
            $plant = DisplayPlant::where('name', $plantName)->first();
            
            if ($plant) {
                $plant->update($careData);
                $this->command->info("Updated care information for: {$plantName}");
            } else {
                $this->command->warn("Plant not found: {$plantName}");
            }
        }

        $this->command->info('Plant care information seeding completed!');
    }
}
